spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    driver-class-name: org.postgresql.Driver
    username: postgres
#    password: postgres
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
#      ddl-auto: update
    ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
  file:
    name: logs/libraryapi.log
  level:
    io.github.eduardoconceicao90: TRACE
    root: WARN
    org:
      hibernate: INFO
      springframework:
        web: DEBUG
        security: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9090

springdoc:
  override-with-generic-response: false